volumes:
  n8n_data:

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    container_name: nlanskov-n8n
    ports:
      - 5678:5678
    environment:
      #N8N_HOST: localhost
      #N8N_PORT: 5678
      WEBHOOK_URL: http://localhost:5678/
      GENERIC_TIMEZONE: Europe/Istanbul
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
    volumes:
      - n8n_data:/home/node/.n8n     # sqlite + creds (encrypted)
