volumes:
  n8n_data:

services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    container_name: n8n
    ports:
      - 5678:5678
    environment:
      # --- n8n basics ---
      N8N_HOST: ${N8N_HOST}
      N8N_PORT: 5678
      WEBHOOK_URL: ${WEBHOOK_URL}   # e.g. http://your.domain.com/ (no https)
      GENERIC_TIMEZONE: Europe/Istanbul

      # --- Security (UI basic auth) ---
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: ${N8N_BASIC_AUTH_USER}
      N8N_BASIC_AUTH_PASSWORD: ${N8N_BASIC_AUTH_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}

      # keep noise low on tiny instances
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_VERSION_NOTIFICATIONS_ENABLED: "false"
    volumes:
      - n8n_data:/home/node/.n8n     # sqlite + creds (encrypted)
